### ISSUE TITLE
Publishing 1.0.4 in Clojars

### ISSUE THREAD

**Issue by coleshaw** [jdhollis/forecast-clojure#5]
You updated the code in Oct 2016 to `1.0.4` with the new `api.darksky.net` URL, but you didn't push this update out to Clojars (it's still on `1.0.3`). Can you please publish the `1.0.4`?

**Comment by jdhollis** [comment]
In all honesty, anyone looking to use this library going forward would probably be better off writing their own functions from scratch. This is an incredibly thin wrapper that makes some decisions about HTTP & JSON libraries. Otherwise, it just returns raw JSON from the API. In retrospect, it probably should have remained a utility function in the project I extracted it from.

Leaving this note here for posterity and archiving the repository.
